<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="17336" started-at="2020-04-23T00:05:07Z" finished-at="2020-04-23T00:05:25Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="17336" started-at="2020-04-23T00:05:07Z" finished-at="2020-04-23T00:05:25Z">
      <class name="ExtentReports.ExtentReports.Test2">
        <test-method status="FAIL" signature="googleTitleValidation()[pri:0, instance:ExtentReports.ExtentReports.Test2@ae45eb6]" name="googleTitleValidation" duration-ms="11411" started-at="2020-04-23T00:05:08Z" finished-at="2020-04-23T00:05:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at ExtentReports.ExtentReports.Test2.googleTitleValidation(Test2.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- googleTitleValidation -->
      </class> <!-- ExtentReports.ExtentReports.Test2 -->
      <class name="ExtentReports.ExtentReports.Test3">
        <test-method status="FAIL" signature="editBoxValidation()[pri:0, instance:ExtentReports.ExtentReports.Test3@59f99ea]" name="editBoxValidation" duration-ms="12352" started-at="2020-04-23T00:05:08Z" finished-at="2020-04-23T00:05:20Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at ExtentReports.ExtentReports.Test3.editBoxValidation(Test3.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editBoxValidation -->
      </class> <!-- ExtentReports.ExtentReports.Test3 -->
      <class name="ExtentReports.ExtentReports.Test1">
        <test-method status="PASS" signature="initialDemo()[pri:0, instance:ExtentReports.ExtentReports.Test1@68c4039c]" name="initialDemo" duration-ms="17120" started-at="2020-04-23T00:05:08Z" finished-at="2020-04-23T00:05:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialDemo -->
      </class> <!-- ExtentReports.ExtentReports.Test1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
